# Generated by Django 4.0.4 on 2022-05-02 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.CharField(max_length=70, null=True)),
                ('number', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('section_type', models.CharField(choices=[('LECTURE', 'Lecture'), ('LAB', 'Lab'), ('DISCUSSION', 'Discussion')], default='LAB', max_length=30)),
                ('location', models.CharField(max_length=20)),
                ('start_time', models.CharField(max_length=20)),
                ('end_time', models.CharField(max_length=20)),
                ('week_days', models.CharField(choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('R', 'Thursday'), ('F', 'Friday'), ('S', 'Saturday'), ('U', 'Sunday')], max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('account_type', models.CharField(choices=[('Supervisor', 'Supervisor'), ('Instructor', 'Instructor'), ('TA', 'TA')], max_length=20)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=10)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('office_hours_days', models.CharField(blank=True, max_length=100)),
                ('office_hours_times', models.CharField(blank=True, max_length=100)),
                ('office_hours_room', models.CharField(blank=True, max_length=100)),
                ('skills', models.CharField(blank=True, max_length=300)),
                ('courses', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TAToProfessor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ProjectApp.user')),
                ('ta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ProjectApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='TAToCourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ProjectApp.course')),
                ('ta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ProjectApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='SectionToCourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ProjectApp.course')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ProjectApp.section')),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ProjectApp.user'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ProjectApp.user'),
        ),
    ]
