# Generated by Django 4.0.4 on 2022-05-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0002_remove_user_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='week_days',
            field=models.CharField(choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('R', 'Thursday'), ('F', 'Friday'), ('S', 'Saturday'), ('U', 'Sunday'), ('MWF', 'Monday, Wednesday, Friday'), ('MW', 'Monday, Wednesday'), ('TR', 'Tuesday, Thursday')], max_length=70),
        ),
        migrations.DeleteModel(
            name='TAToProfessor',
        ),
    ]
